[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["src/generated/prisma/**/*", "node_modules/.prisma/**/*", "node_modules/@prisma/client/**/*"]
